# Generated by Django 4.0.4 on 2022-05-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_route_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='latitude',
            new_name='destination_latitude',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='longitude',
            new_name='destination_longitude',
        ),
        migrations.AddField(
            model_name='route',
            name='starting_latitude',
            field=models.DecimalField(decimal_places=6, default=51, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='starting_longitude',
            field=models.DecimalField(decimal_places=6, default=52, max_digits=9),
            preserve_default=False,
        ),
    ]
