# Generated by Django 4.0.4 on 2022-05-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_rename_latitude_route_destination_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
