# Generated by Django 4.0.4 on 2022-05-07 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_route_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='owner',
        ),
    ]
