# Generated by Django 4.0.4 on 2022-05-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_route_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
