# Generated by Django 4.0.4 on 2022-05-10 22:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_route_route_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='post_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
