# Generated by Django 4.0.4 on 2022-05-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_route_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='distance',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='duration',
            field=models.CharField(default=3, max_length=255),
            preserve_default=False,
        ),
    ]
